const CHARACTERS_LIST = 'CHARACTERS_LIST';
const CHARACTERS_LIST_REQUEST_START = 'CHARACTERS_LIST_REQUEST_START';
const CHARACTERS_LIST_REQUEST_FAIL = 'CHARACTERS_LIST_REQUEST_FAIL';
const CHARACTER_CREATE = 'CHARACTER_CREATE';
const CHARACTER_EDIT = 'CHARACTER_EDIT';
const CHARACTER_DELETE = 'CHARACTER_DELETE';

const types = {
  CHARACTERS_LIST,
  CHARACTERS_LIST_REQUEST_START,
  CHARACTERS_LIST_REQUEST_FAIL,
  CHARACTER_CREATE,
  CHARACTER_EDIT,
  CHARACTER_DELETE,
};

export default types;
