const QUOTES_LIST = 'QUOTES_LIST';
const QUOTES_LIST_REQUEST_START = 'QUOTES_LIST_REQUEST_START';
const QUOTES_LIST_REQUEST_FAIL = 'QUOTES_LIST_REQUEST_FAIL';
const QUOTE_CREATE = 'QUOTE_CREATE';
const QUOTE_EDIT = 'QUOTE_EDIT';
const QUOTE_DELETE = 'QUOTE_DELETE';

const types = {
  QUOTES_LIST,
  QUOTES_LIST_REQUEST_START,
  QUOTES_LIST_REQUEST_FAIL,
  QUOTE_CREATE,
QUOTE_EDIT,
QUOTE_DELETE,

};

export default types;
