const DEATHS_LIST = 'DEATHS_LIST';
const DEATHS_LIST_REQUEST_START = 'DEATHS_LIST_REQUEST_START';
const DEATHS_LIST_REQUEST_FAIL = 'DEATHS_LIST_REQUEST_FAIL';
const DEATH_CREATE = 'DEATH_CREATE';
const DEATH_EDIT = 'DEATH_EDIT';
const DEATH_DELETE = 'DEATH_DELETE';

const types = {
  DEATHS_LIST,
  DEATHS_LIST_REQUEST_START,
  DEATHS_LIST_REQUEST_FAIL,
  DEATH_CREATE,
  DEATH_EDIT,
  DEATH_DELETE,
};

export default types;


