const EPISODES_LIST = 'EPISODES_LIST';
const EPISODES_LIST_REQUEST_START = 'EPISODES_LIST_REQUEST_START';
const EPISODES_LIST_REQUEST_FAIL = 'EPISODES_LIST_REQUEST_FAIL';
const EPISODE_CREATE = 'EPISODE_CREATE';
const EPISODE_EDIT = 'EPISODE_EDIT';
const EPISODE_DELETE = 'EPISODE_DELETE';

const types = {
  EPISODES_LIST,
  EPISODES_LIST_REQUEST_START,
  EPISODES_LIST_REQUEST_FAIL,
  EPISODE_CREATE,
  EPISODE_EDIT,
  EPISODE_DELETE,
};

export default types;
